### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Demirrr** [anonymous-dense-submission/DensE#2]
Hello all,

I have a question pertaining to the reported results.

The equations provided in the appendix of [You CAN Teach an Old Dog New Tricks! On Training Knowledge Graph Embeddings](https://openreview.net/forum?id=BkxSmlBFvr) show the calculation of MRR. In some works--including 
[Tucker](https://www.aclweb.org/anthology/D19-1522/) or [Hyper](https://link.springer.com/chapter/10.1007/978-3-030-30493-5_52), MRR calculated through prediction of objects/tails only given subjects and relations.

However, in DensE, I seem to fail to understand the rationale of [implementation of evaluation](https://github.com/anonymous-dense-submission/DensE/blob/e9de02c9c7032b3899974c3dac051325a69a3804/codes/dataloader.py#L179).

Cheers

**Comment by luhaonan20** [comment]
Hi, 

Thank you for your comments! The evaluation procedure is the same as the code of [RotatE ICLR2019](https://github.com/DeepGraphLearning/KnowledgeGraphEmbedding/blob/master/codes/model.py).

The logic should be the same as you mentioned in Tucker or Hyper. For example, for the "tail-batch" case during the validation, we fix the heads (subjects) and relation in the test dataset, the tail (subjects) candidate is scoring cross all nodes in the graph. Then we rank the predicted scores and compare with the ground truth candidate to get the MRR, MR, Hits@1, Hits@3, and Hits@10.

**Comment by Demirrr** [comment]
Dear @luhaonan20,

thank you for your concise answer. To be 100% sure:

Does link prediction performances in Table 1 of DensE correspond link prediction performances in "tail-batch" case or mean of "tail-batch" and "head-batch" cases ?

**Comment by luhaonan20** [comment]
Dear Demirrr,

It's the mean of "tail-batch" and "head-batch" :)

Cheers

**Comment by Demirrr** [comment]
Appreciated @luhaonan20
