### ISSUE TITLE
Aplication's output

### ISSUE THREAD

**Issue by aalexandrasilva** [anonymous-dense-submission/DensE#5]
Hello,

I was going through the resulting relations' embeddings and noticed there are double the amount of relations in these files, in comparison to the number of relations present in the input graph. I understand this is due to **reciprocal learning**.

However I am struggling with understanding the interpretation of the resulting relations' embeddings.

How can I get a relation's embedding from these files? 
Given a KG with 11 relations, would it be safe to assume that the embeddings present in row 0 and in row 11 correspond to the embeddings of relation with ID 0 and the embedding of its inverse relation?

Thanks in advance,
Alexandra Silva

**Comment by nlp-anonymous-happy** [comment]
> Hello,
> 
> I was going through the resulting relations' embeddings and noticed there are double the amount of relations in these files, in comparison to the number of relations present in the input graph. I understand this is due to **reciprocal learning**.
> 
> However I am struggling with understanding the interpretation of the resulting relations' embeddings.
> 
> How can I get a relation's embedding from these files?
> Given a KG with 11 relations, would it be safe to assume that the embeddings present in row 0 and in row 11 correspond to the embeddings of relation with ID 0 and the embedding of its inverse relation?
> 
> Thanks in advance,
> Alexandra Silva

Hi,

Yes, you are right. (Refer the function around Line 176 in run_DensE.py)

Cheers,
Haonan

**Comment by aalexandrasilva** [comment]
Thank you 👍
